@startuml
package "Entities" #DDD{
  
  abstract User <<abstract>>
  interface Editable <<Interface>>
  User <|-- Student
  User <|-- Monitor
  User <|-- Professor
  Editable <|-- Monitor
  Editable <|-- Professor
  User "user" -- "comments" Comment
  Comment "partner" -- "child" Comment
  Comment "comments" -- "partner" Version
  Article "articles" -- "author" Professor
  Article -- "actual" Version
  Article -- "versions" Version
  Editable -- Version

}
@enduml